/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import static controller.MenuOrganizatorControl.changeButtonColor;
import static controller.StartControl.pushLoginButton;
import static controller.StartControl.startCheckBox;
import static controller.StartControl.startFocusGained;
import static controller.StartControl.startFocusLost;
import java.awt.Color;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import model.Administrator;
import model.Organizator;
import model.Player;

/**
 *
 * @author Freddy A. Fernández
 */
public class MenuDriveTournament extends javax.swing.JFrame {
    
    private List<Organizator> organizator;
    private List<Player> player;
    private List<Administrator> administrator;

    /**
     * Creates new form start
     * @param organizator
     * @param player
     * @param administrator
     */
    public MenuDriveTournament(List<Organizator> organizator, List<Player> player, List<Administrator> administrator) {
        this.organizator = organizator;
        this.player = player;
        this.administrator = administrator;
        this.setUndecorated(true);
        initComponents();
        this.setResizable(true);
        this.setLocationRelativeTo(null);
        this.newIcon();
    }
    
    private void newIcon(){
        Image icon = new ImageIcon(getClass().getResource("/images/logoTamanacoSinFuego.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Banner = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        entradaNombreTorneo1 = new javax.swing.JTextField();
        jSeparator58 = new javax.swing.JSeparator();
        jSeparator60 = new javax.swing.JSeparator();
        botonSeguirIngresarDatosTorneo1 = new javax.swing.JButton();
        botonRegresarIngresarDatosTorneo1 = new javax.swing.JButton();
        entradaNombreTorneo3 = new javax.swing.JTextField();
        jLabel145 = new javax.swing.JLabel();
        jSeparator61 = new javax.swing.JSeparator();
        jSeparator62 = new javax.swing.JSeparator();
        entradaFechaNacimientoJugador1 = new javax.swing.JTextField();
        jLabel254 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        entradaNombreTorneo2 = new javax.swing.JTextField();
        jSeparator59 = new javax.swing.JSeparator();
        jLabel247 = new javax.swing.JLabel();
        jLabel262 = new javax.swing.JLabel();
        jSeparator71 = new javax.swing.JSeparator();
        entradaNombreTorneo5 = new javax.swing.JTextField();
        jLabel272 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        entradaNombreTorneo4 = new javax.swing.JTextField();
        jSeparator63 = new javax.swing.JSeparator();
        modificarMatch = new javax.swing.JButton();
        botonRegresarIngresarDatosTorneo2 = new javax.swing.JButton();
        jSeparator72 = new javax.swing.JSeparator();
        entradaFechaNacimientoJugador2 = new javax.swing.JTextField();
        jLabel270 = new javax.swing.JLabel();
        jSeparator74 = new javax.swing.JSeparator();
        entradaNombreTorneo6 = new javax.swing.JTextField();
        jLabel273 = new javax.swing.JLabel();
        entradaNombreTorneo7 = new javax.swing.JTextField();
        jSeparator75 = new javax.swing.JSeparator();
        jLabel274 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel275 = new javax.swing.JLabel();
        entradaNombreTorneo8 = new javax.swing.JTextField();
        jSeparator76 = new javax.swing.JSeparator();
        jSeparator77 = new javax.swing.JSeparator();
        jLabel276 = new javax.swing.JLabel();
        jLabel277 = new javax.swing.JLabel();
        botonSeguirIngresarDatosTorneo2 = new javax.swing.JButton();
        botonRegresarIngresarDatosTorneo3 = new javax.swing.JButton();
        entradaNombreTorneo9 = new javax.swing.JTextField();
        jLabel280 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(51, 51, 51));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TAMANACO TENNIS LEAGUE");
        background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 430, -1));

        jLabel9.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Break Point Tamanaco");
        jLabel9.setToolTipText("");
        background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 150, -1));

        Banner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banner.jpg"))); // NOI18N
        Banner.setText("jLabel1");
        Banner.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Banner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BannerMouseClicked(evt);
            }
        });
        background.add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 980, 110));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/matchPhoto (1) (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 0, -1, -1));

        jLabel100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tamanacoLogoPequenio.png"))); // NOI18N
        jPanel1.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel112.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(153, 153, 153));
        jLabel112.setText("aGREGAR partido...");
        jPanel1.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, 60));

        jLabel36.setBackground(new java.awt.Color(51, 51, 51));
        jLabel36.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel36.setText("Ingresar CI del JUGADOR 1:");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 230, 30));

        entradaNombreTorneo1.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        entradaNombreTorneo1.setForeground(new java.awt.Color(153, 153, 153));
        entradaNombreTorneo1.setText("Ingresar Numero de Cedula");
        entradaNombreTorneo1.setBorder(null);
        entradaNombreTorneo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo1FocusLost(evt);
            }
        });
        entradaNombreTorneo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNombreTorneo1ActionPerformed(evt);
            }
        });
        jPanel1.add(entradaNombreTorneo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));
        jPanel1.add(jSeparator58, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 350, 10));
        jPanel1.add(jSeparator60, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 330, 10));

        botonSeguirIngresarDatosTorneo1.setBackground(new java.awt.Color(36, 20, 188));
        botonSeguirIngresarDatosTorneo1.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        botonSeguirIngresarDatosTorneo1.setForeground(new java.awt.Color(255, 255, 255));
        botonSeguirIngresarDatosTorneo1.setText("Agregar");
        botonSeguirIngresarDatosTorneo1.setBorder(null);
        botonSeguirIngresarDatosTorneo1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonSeguirIngresarDatosTorneo1MouseMoved(evt);
            }
        });
        botonSeguirIngresarDatosTorneo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSeguirIngresarDatosTorneo1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSeguirIngresarDatosTorneo1MouseExited(evt);
            }
        });
        botonSeguirIngresarDatosTorneo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeguirIngresarDatosTorneo1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonSeguirIngresarDatosTorneo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 140, 40));

        botonRegresarIngresarDatosTorneo1.setBackground(new java.awt.Color(36, 20, 188));
        botonRegresarIngresarDatosTorneo1.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        botonRegresarIngresarDatosTorneo1.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresarIngresarDatosTorneo1.setText("REGRESAR");
        botonRegresarIngresarDatosTorneo1.setBorder(null);
        botonRegresarIngresarDatosTorneo1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonRegresarIngresarDatosTorneo1MouseMoved(evt);
            }
        });
        botonRegresarIngresarDatosTorneo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresarIngresarDatosTorneo1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarIngresarDatosTorneo1MouseExited(evt);
            }
        });
        botonRegresarIngresarDatosTorneo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarIngresarDatosTorneo1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegresarIngresarDatosTorneo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 140, 40));

        entradaNombreTorneo3.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        entradaNombreTorneo3.setForeground(new java.awt.Color(153, 153, 153));
        entradaNombreTorneo3.setText("Ingresar numero de cedula");
        entradaNombreTorneo3.setBorder(null);
        entradaNombreTorneo3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo3FocusLost(evt);
            }
        });
        entradaNombreTorneo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNombreTorneo3ActionPerformed(evt);
            }
        });
        jPanel1.add(entradaNombreTorneo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel145.setBackground(new java.awt.Color(51, 51, 51));
        jLabel145.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel145.setText("Ingresar CI del JUGADOR 2:");
        jPanel1.add(jLabel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 30));
        jPanel1.add(jSeparator61, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 350, 10));
        jPanel1.add(jSeparator62, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 350, 10));

        entradaFechaNacimientoJugador1.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        entradaFechaNacimientoJugador1.setForeground(new java.awt.Color(153, 153, 153));
        entradaFechaNacimientoJugador1.setText("Ingresar fecha (DD-MM-YYYY)");
        entradaFechaNacimientoJugador1.setBorder(null);
        entradaFechaNacimientoJugador1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entradaFechaNacimientoJugador1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entradaFechaNacimientoJugador1FocusLost(evt);
            }
        });
        entradaFechaNacimientoJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaFechaNacimientoJugador1ActionPerformed(evt);
            }
        });
        jPanel1.add(entradaFechaNacimientoJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        jLabel254.setBackground(new java.awt.Color(51, 51, 51));
        jLabel254.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel254.setText("Ingresar fecha del partido:");
        jPanel1.add(jLabel254, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, 30));

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/matchPhoto (1) (1).jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 0, -1, -1));

        jLabel53.setBackground(new java.awt.Color(51, 51, 51));
        jLabel53.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel53.setText("Ingresar CI del JUGADOR 1:");
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 230, 30));

        entradaNombreTorneo2.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        entradaNombreTorneo2.setForeground(new java.awt.Color(153, 153, 153));
        entradaNombreTorneo2.setText("Ingresar Numero de Cedula");
        entradaNombreTorneo2.setBorder(null);
        entradaNombreTorneo2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo2FocusLost(evt);
            }
        });
        entradaNombreTorneo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNombreTorneo2ActionPerformed(evt);
            }
        });
        jPanel2.add(entradaNombreTorneo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));
        jPanel2.add(jSeparator59, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 230, 10));

        jLabel247.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tamanacoLogoPequenio.png"))); // NOI18N
        jPanel2.add(jLabel247, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel262.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        jLabel262.setForeground(new java.awt.Color(153, 153, 153));
        jLabel262.setText("MODIFICAR partido...");
        jPanel2.add(jLabel262, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, 60));
        jPanel2.add(jSeparator71, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 350, 10));

        entradaNombreTorneo5.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        entradaNombreTorneo5.setForeground(new java.awt.Color(153, 153, 153));
        entradaNombreTorneo5.setText("Ingresar numero de cedula");
        entradaNombreTorneo5.setBorder(null);
        entradaNombreTorneo5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo5FocusLost(evt);
            }
        });
        entradaNombreTorneo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNombreTorneo5ActionPerformed(evt);
            }
        });
        jPanel2.add(entradaNombreTorneo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel272.setBackground(new java.awt.Color(51, 51, 51));
        jLabel272.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel272.setText("INGRESAR ci DEL GANADOR:");
        jPanel2.add(jLabel272, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 30));

        jLabel54.setBackground(new java.awt.Color(51, 51, 51));
        jLabel54.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel54.setText("Ingresar CI del JUGADOR 2:");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 230, 30));

        entradaNombreTorneo4.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        entradaNombreTorneo4.setForeground(new java.awt.Color(153, 153, 153));
        entradaNombreTorneo4.setText("Ingresar Numero de Cedula");
        entradaNombreTorneo4.setBorder(null);
        entradaNombreTorneo4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo4FocusLost(evt);
            }
        });
        entradaNombreTorneo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNombreTorneo4ActionPerformed(evt);
            }
        });
        jPanel2.add(entradaNombreTorneo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));
        jPanel2.add(jSeparator63, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 230, 10));

        modificarMatch.setBackground(new java.awt.Color(36, 20, 188));
        modificarMatch.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        modificarMatch.setForeground(new java.awt.Color(255, 255, 255));
        modificarMatch.setText("Modificar");
        modificarMatch.setBorder(null);
        modificarMatch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                modificarMatchMouseMoved(evt);
            }
        });
        modificarMatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMatchMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarMatchMouseExited(evt);
            }
        });
        modificarMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMatchActionPerformed(evt);
            }
        });
        jPanel2.add(modificarMatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 140, 40));

        botonRegresarIngresarDatosTorneo2.setBackground(new java.awt.Color(36, 20, 188));
        botonRegresarIngresarDatosTorneo2.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        botonRegresarIngresarDatosTorneo2.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresarIngresarDatosTorneo2.setText("REGRESAR");
        botonRegresarIngresarDatosTorneo2.setBorder(null);
        botonRegresarIngresarDatosTorneo2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonRegresarIngresarDatosTorneo2MouseMoved(evt);
            }
        });
        botonRegresarIngresarDatosTorneo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresarIngresarDatosTorneo2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarIngresarDatosTorneo2MouseExited(evt);
            }
        });
        botonRegresarIngresarDatosTorneo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarIngresarDatosTorneo2ActionPerformed(evt);
            }
        });
        jPanel2.add(botonRegresarIngresarDatosTorneo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 140, 40));
        jPanel2.add(jSeparator72, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 350, 10));

        entradaFechaNacimientoJugador2.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        entradaFechaNacimientoJugador2.setForeground(new java.awt.Color(153, 153, 153));
        entradaFechaNacimientoJugador2.setText("Ingresar fecha (DD-MM-YYYY)");
        entradaFechaNacimientoJugador2.setBorder(null);
        entradaFechaNacimientoJugador2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entradaFechaNacimientoJugador2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entradaFechaNacimientoJugador2FocusLost(evt);
            }
        });
        entradaFechaNacimientoJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaFechaNacimientoJugador2ActionPerformed(evt);
            }
        });
        jPanel2.add(entradaFechaNacimientoJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabel270.setBackground(new java.awt.Color(51, 51, 51));
        jLabel270.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel270.setText("Ingresar fecha del partido:");
        jPanel2.add(jLabel270, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 30));
        jPanel2.add(jSeparator74, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 150, 10));

        entradaNombreTorneo6.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        entradaNombreTorneo6.setForeground(new java.awt.Color(153, 153, 153));
        entradaNombreTorneo6.setText("Ingresar Resultado");
        entradaNombreTorneo6.setBorder(null);
        entradaNombreTorneo6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo6FocusLost(evt);
            }
        });
        entradaNombreTorneo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNombreTorneo6ActionPerformed(evt);
            }
        });
        jPanel2.add(entradaNombreTorneo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel273.setBackground(new java.awt.Color(51, 51, 51));
        jLabel273.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel273.setText("Primer set");
        jPanel2.add(jLabel273, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 30));

        entradaNombreTorneo7.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        entradaNombreTorneo7.setForeground(new java.awt.Color(153, 153, 153));
        entradaNombreTorneo7.setText("Ingresar Resultado");
        entradaNombreTorneo7.setBorder(null);
        entradaNombreTorneo7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo7FocusLost(evt);
            }
        });
        entradaNombreTorneo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNombreTorneo7ActionPerformed(evt);
            }
        });
        jPanel2.add(entradaNombreTorneo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));
        jPanel2.add(jSeparator75, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 150, 10));

        jLabel274.setBackground(new java.awt.Color(51, 51, 51));
        jLabel274.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel274.setText("Segundo Set");
        jPanel2.add(jLabel274, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, 30));

        jTabbedPane1.addTab("tab2", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/matchPhoto (1) (1).jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 0, -1, -1));

        jLabel275.setBackground(new java.awt.Color(51, 51, 51));
        jLabel275.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel275.setText("Ingresar CI del JUGADOR 1:");
        jPanel3.add(jLabel275, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 230, 30));

        entradaNombreTorneo8.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        entradaNombreTorneo8.setForeground(new java.awt.Color(153, 153, 153));
        entradaNombreTorneo8.setText("Ingresar Numero de Cedula");
        entradaNombreTorneo8.setBorder(null);
        entradaNombreTorneo8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo8FocusLost(evt);
            }
        });
        entradaNombreTorneo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNombreTorneo8ActionPerformed(evt);
            }
        });
        jPanel3.add(entradaNombreTorneo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));
        jPanel3.add(jSeparator76, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 350, 10));
        jPanel3.add(jSeparator77, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 350, 10));

        jLabel276.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tamanacoLogoPequenio.png"))); // NOI18N
        jPanel3.add(jLabel276, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel277.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        jLabel277.setForeground(new java.awt.Color(153, 153, 153));
        jLabel277.setText("BORRAR partido...");
        jPanel3.add(jLabel277, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, 60));

        botonSeguirIngresarDatosTorneo2.setBackground(new java.awt.Color(36, 20, 188));
        botonSeguirIngresarDatosTorneo2.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        botonSeguirIngresarDatosTorneo2.setForeground(new java.awt.Color(255, 255, 255));
        botonSeguirIngresarDatosTorneo2.setText("ELIMINAR");
        botonSeguirIngresarDatosTorneo2.setBorder(null);
        botonSeguirIngresarDatosTorneo2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonSeguirIngresarDatosTorneo2MouseMoved(evt);
            }
        });
        botonSeguirIngresarDatosTorneo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSeguirIngresarDatosTorneo2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSeguirIngresarDatosTorneo2MouseExited(evt);
            }
        });
        botonSeguirIngresarDatosTorneo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeguirIngresarDatosTorneo2ActionPerformed(evt);
            }
        });
        jPanel3.add(botonSeguirIngresarDatosTorneo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 140, 40));

        botonRegresarIngresarDatosTorneo3.setBackground(new java.awt.Color(36, 20, 188));
        botonRegresarIngresarDatosTorneo3.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        botonRegresarIngresarDatosTorneo3.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresarIngresarDatosTorneo3.setText("REGRESAR");
        botonRegresarIngresarDatosTorneo3.setBorder(null);
        botonRegresarIngresarDatosTorneo3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonRegresarIngresarDatosTorneo3MouseMoved(evt);
            }
        });
        botonRegresarIngresarDatosTorneo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresarIngresarDatosTorneo3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarIngresarDatosTorneo3MouseExited(evt);
            }
        });
        botonRegresarIngresarDatosTorneo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarIngresarDatosTorneo3ActionPerformed(evt);
            }
        });
        jPanel3.add(botonRegresarIngresarDatosTorneo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 140, 40));

        entradaNombreTorneo9.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        entradaNombreTorneo9.setForeground(new java.awt.Color(153, 153, 153));
        entradaNombreTorneo9.setText("Ingresar numero de cedula");
        entradaNombreTorneo9.setBorder(null);
        entradaNombreTorneo9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo9FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entradaNombreTorneo9FocusLost(evt);
            }
        });
        entradaNombreTorneo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNombreTorneo9ActionPerformed(evt);
            }
        });
        jPanel3.add(entradaNombreTorneo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLabel280.setBackground(new java.awt.Color(51, 51, 51));
        jLabel280.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel280.setText("Ingresar CI del JUGADOR 2:");
        jPanel3.add(jLabel280, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, 30));

        jTabbedPane1.addTab("tab3", jPanel3);

        background.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 970, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BannerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BannerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BannerMouseClicked

    private void entradaNombreTorneo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo1FocusGained

    private void entradaNombreTorneo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo1FocusLost

    private void entradaNombreTorneo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaNombreTorneo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo1ActionPerformed

    private void botonSeguirIngresarDatosTorneo1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSeguirIngresarDatosTorneo1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSeguirIngresarDatosTorneo1MouseMoved

    private void botonSeguirIngresarDatosTorneo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSeguirIngresarDatosTorneo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSeguirIngresarDatosTorneo1MouseClicked

    private void botonSeguirIngresarDatosTorneo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSeguirIngresarDatosTorneo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSeguirIngresarDatosTorneo1MouseExited

    private void botonSeguirIngresarDatosTorneo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeguirIngresarDatosTorneo1ActionPerformed
        Player playerOne = organizator.searchPlayer(entradaNombreTorneo1);
        Player playerTwo = organizator.searchPlayer(entradaNombreTorneo3);
        Match match = new Match(playerOne, playerTwo, playerOne, "0-0", "0-0", StringBecomeLocalDate(entradaFechaNacimientoJugador1.getText()));
        jsonMatch.addPerson(match);
        matchList.add(match);
        pestania.setSelectedIndex(3);

        loadMatchesInTable(matchList, tablaPartidos);
    }//GEN-LAST:event_botonSeguirIngresarDatosTorneo1ActionPerformed

    private void botonRegresarIngresarDatosTorneo1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarIngresarDatosTorneo1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarIngresarDatosTorneo1MouseMoved

    private void botonRegresarIngresarDatosTorneo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarIngresarDatosTorneo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarIngresarDatosTorneo1MouseClicked

    private void botonRegresarIngresarDatosTorneo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarIngresarDatosTorneo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarIngresarDatosTorneo1MouseExited

    private void botonRegresarIngresarDatosTorneo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarIngresarDatosTorneo1ActionPerformed
        pestania.setSelectedIndex(3);
    }//GEN-LAST:event_botonRegresarIngresarDatosTorneo1ActionPerformed

    private void entradaNombreTorneo3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo3FocusGained

    private void entradaNombreTorneo3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo3FocusLost

    private void entradaNombreTorneo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaNombreTorneo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo3ActionPerformed

    private void entradaFechaNacimientoJugador1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaFechaNacimientoJugador1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaFechaNacimientoJugador1FocusGained

    private void entradaFechaNacimientoJugador1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaFechaNacimientoJugador1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaFechaNacimientoJugador1FocusLost

    private void entradaFechaNacimientoJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaFechaNacimientoJugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaFechaNacimientoJugador1ActionPerformed

    private void entradaNombreTorneo2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo2FocusGained

    private void entradaNombreTorneo2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo2FocusLost

    private void entradaNombreTorneo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaNombreTorneo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo2ActionPerformed

    private void entradaNombreTorneo5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo5FocusGained

    private void entradaNombreTorneo5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo5FocusLost

    private void entradaNombreTorneo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaNombreTorneo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo5ActionPerformed

    private void entradaNombreTorneo4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo4FocusGained

    private void entradaNombreTorneo4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo4FocusLost

    private void entradaNombreTorneo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaNombreTorneo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo4ActionPerformed

    private void modificarMatchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMatchMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarMatchMouseMoved

    private void modificarMatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMatchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarMatchMouseClicked

    private void modificarMatchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMatchMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarMatchMouseExited

    private void modificarMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMatchActionPerformed
        Player playerA = organizator.searchPlayer(entradaNombreTorneo2);
        Player playerB = organizator.searchPlayer(entradaNombreTorneo4);
        Player winner = organizator.searchPlayer(entradaNombreTorneo5);
        String setOne = entradaNombreTorneo6.getText(), setTwo = entradaNombreTorneo7.getText();
        LocalDate date = StringBecomeLocalDate(entradaFechaNacimientoJugador2.getText());
        Match match = new Match(playerA, playerB, winner, setOne, setTwo, date);
        foundMatch(matchList, playerA.getId(), playerB.getId(), match);
        jsonMatch.updatePerson(match);
        pestania.setSelectedIndex(3);

    }//GEN-LAST:event_modificarMatchActionPerformed

    private void botonRegresarIngresarDatosTorneo2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarIngresarDatosTorneo2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarIngresarDatosTorneo2MouseMoved

    private void botonRegresarIngresarDatosTorneo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarIngresarDatosTorneo2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarIngresarDatosTorneo2MouseClicked

    private void botonRegresarIngresarDatosTorneo2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarIngresarDatosTorneo2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarIngresarDatosTorneo2MouseExited

    private void botonRegresarIngresarDatosTorneo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarIngresarDatosTorneo2ActionPerformed
        pestania.setSelectedIndex(3);
    }//GEN-LAST:event_botonRegresarIngresarDatosTorneo2ActionPerformed

    private void entradaFechaNacimientoJugador2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaFechaNacimientoJugador2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaFechaNacimientoJugador2FocusGained

    private void entradaFechaNacimientoJugador2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaFechaNacimientoJugador2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaFechaNacimientoJugador2FocusLost

    private void entradaFechaNacimientoJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaFechaNacimientoJugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaFechaNacimientoJugador2ActionPerformed

    private void entradaNombreTorneo6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo6FocusGained

    private void entradaNombreTorneo6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo6FocusLost

    private void entradaNombreTorneo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaNombreTorneo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo6ActionPerformed

    private void entradaNombreTorneo7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo7FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo7FocusGained

    private void entradaNombreTorneo7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo7FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo7FocusLost

    private void entradaNombreTorneo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaNombreTorneo7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo7ActionPerformed

    private void entradaNombreTorneo8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo8FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo8FocusGained

    private void entradaNombreTorneo8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo8FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo8FocusLost

    private void entradaNombreTorneo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaNombreTorneo8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo8ActionPerformed

    private void botonSeguirIngresarDatosTorneo2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSeguirIngresarDatosTorneo2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSeguirIngresarDatosTorneo2MouseMoved

    private void botonSeguirIngresarDatosTorneo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSeguirIngresarDatosTorneo2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSeguirIngresarDatosTorneo2MouseClicked

    private void botonSeguirIngresarDatosTorneo2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSeguirIngresarDatosTorneo2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSeguirIngresarDatosTorneo2MouseExited

    private void botonSeguirIngresarDatosTorneo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeguirIngresarDatosTorneo2ActionPerformed
        Player playerA = organizator.searchPlayer(entradaNombreTorneo2);
        Player playerB = organizator.searchPlayer(entradaNombreTorneo4);
        deleteMatch(matchList, playerA.getId(), playerB.getId());
        pestania.setSelectedIndex(3);
    }//GEN-LAST:event_botonSeguirIngresarDatosTorneo2ActionPerformed

    private void botonRegresarIngresarDatosTorneo3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarIngresarDatosTorneo3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarIngresarDatosTorneo3MouseMoved

    private void botonRegresarIngresarDatosTorneo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarIngresarDatosTorneo3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarIngresarDatosTorneo3MouseClicked

    private void botonRegresarIngresarDatosTorneo3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarIngresarDatosTorneo3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarIngresarDatosTorneo3MouseExited

    private void botonRegresarIngresarDatosTorneo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarIngresarDatosTorneo3ActionPerformed
        pestania.setSelectedIndex(3);
    }//GEN-LAST:event_botonRegresarIngresarDatosTorneo3ActionPerformed

    private void entradaNombreTorneo9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo9FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo9FocusGained

    private void entradaNombreTorneo9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaNombreTorneo9FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo9FocusLost

    private void entradaNombreTorneo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaNombreTorneo9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreTorneo9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDriveTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner;
    private javax.swing.JPanel background;
    private javax.swing.JButton botonRegresarIngresarDatosTorneo1;
    private javax.swing.JButton botonRegresarIngresarDatosTorneo2;
    private javax.swing.JButton botonRegresarIngresarDatosTorneo3;
    private javax.swing.JButton botonSeguirIngresarDatosTorneo1;
    private javax.swing.JButton botonSeguirIngresarDatosTorneo2;
    private javax.swing.JTextField entradaFechaNacimientoJugador1;
    private javax.swing.JTextField entradaFechaNacimientoJugador2;
    private javax.swing.JTextField entradaNombreTorneo1;
    private javax.swing.JTextField entradaNombreTorneo2;
    private javax.swing.JTextField entradaNombreTorneo3;
    private javax.swing.JTextField entradaNombreTorneo4;
    private javax.swing.JTextField entradaNombreTorneo5;
    private javax.swing.JTextField entradaNombreTorneo6;
    private javax.swing.JTextField entradaNombreTorneo7;
    private javax.swing.JTextField entradaNombreTorneo8;
    private javax.swing.JTextField entradaNombreTorneo9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel247;
    private javax.swing.JLabel jLabel254;
    private javax.swing.JLabel jLabel262;
    private javax.swing.JLabel jLabel270;
    private javax.swing.JLabel jLabel272;
    private javax.swing.JLabel jLabel273;
    private javax.swing.JLabel jLabel274;
    private javax.swing.JLabel jLabel275;
    private javax.swing.JLabel jLabel276;
    private javax.swing.JLabel jLabel277;
    private javax.swing.JLabel jLabel280;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator58;
    private javax.swing.JSeparator jSeparator59;
    private javax.swing.JSeparator jSeparator60;
    private javax.swing.JSeparator jSeparator61;
    private javax.swing.JSeparator jSeparator62;
    private javax.swing.JSeparator jSeparator63;
    private javax.swing.JSeparator jSeparator71;
    private javax.swing.JSeparator jSeparator72;
    private javax.swing.JSeparator jSeparator74;
    private javax.swing.JSeparator jSeparator75;
    private javax.swing.JSeparator jSeparator76;
    private javax.swing.JSeparator jSeparator77;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton modificarMatch;
    // End of variables declaration//GEN-END:variables
}
